#!/bin/bash
pname=$(basename "$0")
usage="$pname [-h|--help]
Features:
  Make a list (text file) of package names of Android applications in the ./apps directory.
  The name of this list file is '@list'.
Options:
  -h|--help
    This help message is displayed."

declare -a opts
while true; do
  case "$1" in
  -|--) break;;
  --*) opts=("$1"); shift;;
  -*) for n in $(seq 1 $((${#1}-1))); do opts[$n]="-${1:$n:1}"; done; shift;;
  *) break;;
  esac
  for opt in "${opts[@]}"; do
    case "$opt" in
    -h|--help) echo "$usage"; exit 0;;
    -*) echo "$usage"; exit 1;;
    *) break;;
    esac
  done
done
test $# -ne 0 && { echo "$pname: extra arguments.">&2; echo "$usage"; exit 1;}

pkglist=@list
appsdir=apps

(
  test "$(basename $(pwd))" = apps || {
    test -d "$appsdir" || { echo "$appsdir: no such a directory here.">&2; exit 2;}
    cd apps
  }
  
  test -e ../"$pkglist" && rm -f ../"$pkglist"
  ls *.{apk,ab} | sed 's|-..*\.apk$||;s|\.apk||;;s|\.ab$||' | sort | uniq >../"$pkglist" ||
    { echo "$pname: abort.">&2; exit 3; }
)
