#!/bin/bash
pname=$(basename "$0")
usage="$pname [{-s|--saadir} SaaDir] [{-t|--target} {apk|ab|apk,ab}] [-l|--list|-q|--quiet|-v|--verbose|-n|--dryrun|--nolog]
$pname [-h|--help]"
targets='apk,ab'
listp=false
quietp=false
verbosep=false
dryrunp=false
nologp=false
while true; do
  case "$1" in
  -s|--saadir) SAADIR="$2"; shift 2;;
  -t|--target) targets="$2"; shift 2;;
  -l|--list) listp=true; shift;;
  -q|--quiet) quietp=true; shift;;
  -v|--verbose) verbosep=true; shift;;
  -n|--dryrun) dryrunp=true; verbosep=true; shift;;
  --nolog) nologp=true; shift;;
  -*) echo "$usage"; exit 1;;
  *) break;;
  esac
done
targets=$(IFS=$' \t\n,'; echo $targets)
test $# -ne 0 && { echo "$usage"; exit 1;}

dname=$(dirname "$0")
case "$dname" in /*);; *) dname="$(pwd)/$dname";; esac

test -z "$SAADIR" && { echo "Please set envvar: SAADIR or use -s|--saadir option.">&2; exit 2;}
saadir="$SAADIR"/apps
saadir_escaped="$saadir"  # TODO: to be regexp escaped
pkglist="$SAADIR"/@list
#blacklist=@blacklist
pkgondev=@pkgondev
pkgtoput=@pkgtoput
#filetoput=@filetoput
test -d "$saadir" ||
  { echo "$saadir: no such a (applications) directory.">&2; exit 3;}
test -r "$pkglist" ||
  { echo "$pkglist: no such a (packages list) file.">&2; exit 4;}

adev="$(adb devices -l)"
dev=$(echo "$adev" | adb-parsedev -b -o -r -s -u model) || exit 11
stamp=$(date +%Y%m%d-%H%M%S)
log="log-$dev-$stamp-put"
$listp && log="log-$dev-$stamp-putlist"
$nologp && log=/dev/null

(
  $quietp || echo "device: $dev">&2
  $quietp || echo "timestamp: $stamp">&2
  $quietp || echo "SAADIR=$SAADIR">&2

  get-android-apps list -3 >"$pkgondev"
  set-complement "$pkglist" "$pkgondev" >"$pkgtoput"

  if $listp; then
    echo -------- Packages to put:
    cat "$pkgtoput"
    echo -------- end of Packages to put:
    rm "$pkgtoput"
  else
    for obj in $targets; do
      set put-android-apps $obj $(sed "s|^|$saadir_escaped|;s|$|.$obj|" "$pkgtoput")
      $verbosep && echo "$@"
      $dryrunp || "$@"
    done
    mv "$pkgondev" "$pkgondev-$dev-$stamp"
    mv "$pkgtoput" "$pkgtoput-$stamp-$dev"
  fi
) 2>&1 | tee "$log"
