#!/bin/bash
pname=$(basename "$0")
dname=$(dirname "$0")
case "$dname" in /*);; *) dname="$(pwd)/$dname";; esac
usage="$pname [PackageListFile [...]]
$pname {-h|--help}
Features:
  Make a list (text file) of package names and labels of Android applications from '@list' file. 
Options:
  -h|--help
    This help message is displayed."

source "$dname/saa-environ.sh"

helpp=false
opterrp=false
declare -a opts
while true; do
  case "$1" in
  -|--) break;;
  --*) opts=("$1"); shift;;
  -*) for n in $(seq 1 $((${#1}-1))); do opts[$n]="-${1:$n:1}"; done; shift;;
  *) break;;
  esac
  for opt in "${opts[@]}"; do
    case "$opt" in
    -h|--help) helpp=true;;
    -*) echo "$opt: unknown option.">&2; opterrp=true;;
    esac
  done
done
$opterrp && exit 1
$helpp && { echo "$usage"; exit;}

test $# -eq 0 && {
  default="$pkglist"
  test "$(basename $(pwd))" = "$appsdir" && default="../$default"
  set "$default"
}

for list; do 
  cat "$list" | get-android-app-name -p - ||
    { echo "$pname: abort.">&2; exit 2; }
done
