#!/bin/bash
pname=$(basename "$0")
dname=$(dirname "$0")
case "$dname" in /*);; *) dname="$(pwd)/$dname";; esac
usage="$pname [-h|--help]
Features:
  Make a list (text file) of package names and labels of Android applications from '@list' file. 
  The name of this list file is '@description'.
Options:
  -h|--help
    This help message is displayed."

source "$dname/saa-environ.sh"

helpp=false
opterrp=false
declare -a opts
while true; do
  case "$1" in
  -|--) break;;
  --*) opts=("$1"); shift;;
  -*) for n in $(seq 1 $((${#1}-1))); do opts[$n]="-${1:$n:1}"; done; shift;;
  *) break;;
  esac
  for opt in "${opts[@]}"; do
    case "$opt" in
    -h|--help) helpp=true;;
    -*) echo "$opt: unknown option.">&2; opterrp=true;;
    esac
  done
done
$opterrp && exit 1
$helpp || test $# -ne 0 && { echo "$usage"; exit;}
test $# -ne 0 && { echo "$pname: extra arguments.">&2; echo "$usage"; exit 1;}

(
  test "$(basename $(pwd))" = "$appsdir" && cd ..
  test -r "$pkglist" || { echo "$pkglist: no such a file here.">&2; exit 2;}
  
  cat "$pkglist" | get-android-app-name -p - >"$desclist" ||
    { echo "$pname: abort.">&2; exit 3; }
)
