#!/bin/bash
pname=$(basename "$0")
dname=$(dirname "$0")
case "$dname" in /*);; *) dname="$(pwd)/$dname";; esac
source "$dname/saa-environ.sh"
usage="$pname [Options] [PackageDir|AppsDir]
$pname [-h|--help]
Features:
  Make a list (text file) of package names of Android applications in the ./apps directory.
  The name of this list file is '@list'.
Options:
  -c|--stdout|--to-stdout
    output to stdout (default: output to $pkglist).
  -h|--help
    This help message is displayed."

stdoutp=false
helpp=false
opterrp=false
declare -a opts
while true; do
  case "$1" in
  -|--) break;;
  --*) opts=("$1"); shift;;
  -*) for n in $(seq 1 $((${#1}-1))); do opts[$n]="-${1:$n:1}"; done; shift;;
  *) break;;
  esac
  for opt in "${opts[@]}"; do
    case "$opt" in
    -c|--stdout|--to-stdout)stdoutp=true;;
    -h|--help) helpp=true;;
    -*) echo "$opt: unknown option.">&2; opterrp=true;;
    esac
  done
done
$opterrp && exit 1
$helpp && { echo "$usage"; exit;}

test $# -eq 0 && {
  default="."
  test "$(basename $(pwd))" = "$appsdir" && default=".."
  set "$default"
}

make_pkglist() {
  sed -n '/^[ \t]*#/p'
  ls *.{apk,ab} 2>/dev/null | sed 's|-..*\.apk$||;s|\.apk||;;s|\.ab$||' | sort | uniq
}

for dir; do
  (
    test -d "$dir" || { echo "$dir: no such a directory here.">&2; exit 2;}
    cd "$dir"
    test "$(basename $(pwd))" = "$appsdir" || {
      test -d "$appsdir" || { echo "$appsdir: no such a directory here.">&2; exit 3;}
      cd apps
    }
    
    $stdoutp || {
      output="$desclist"
      outbk="$output.bk"
      test -e "$output" && mv "$output" "$outbk"
    }
    tmpf="$(mktemp)"
    if test -f "../$pkglist"; then
      cat "../$pkglist"
    else
      cat /dev/null
    fi >"$tmpf"
    cat "$tmpf" | 
    if $stdoutp; then
      make_pkglist
    else
      make_pkglist >"../$pkglist"
    fi ||
      {
        echo "$pname: abort.">&2
        $stdoutp || mv "$outbk" "$output"
        rm -f "$tmpf"
        exit 4
      }
    rm -f "$tmpf"
  )
done
