#!/bin/sh
pname=$(basename "$0")
dname=$(dirname "$0")
case "$dname" in /*);; *) dname="$(pwd)/$dname";; esac
usage="$pname  [-q|--quiet|-v|--verbose|-n|--dryrun] SourceSAADir NewSAADir
$pname  {-h|--help}
Features:

Options:
  -q|--quiet
    No messages are displayed, except error message.
  -v|--verbose
    Additional messages are displayed. It has precedence over -q|--quiet|-s|--silent.
  -n|--dryrun
    Only messages displayed, No SAADirectory is made.
  -h|--help
    This help message is displayed."

source "$dname/saa-environ.sh"

quietp=false
verbosep=false
drurunp=false
helpp=false
opterrp=false
declare -a opts
while true; do
  case "$1" in
  -|--) break;;
  --*) opts=("$1"); shift;;
  -*) for n in $(seq 1 $((${#1}-1))); do opts[$n]="-${1:$n:1}"; done; shift;;
  *) break;;
  esac
  for opt in "${opts[@]}"; do
    case "$opt" in
    -q|--quiet) quietp=true;;
    -n|--dryrun) dryrunp=true;;
    -v|--verbose) verbosep=true;;
    -h|--help) helpp=true;;
    -*) echo "$opt: unknown option.">&2; opterrp=true;;
    esac
  done
done
$opterrp && exit 1
$helpp || test $# -ne 0 && { echo "$usage"; exit;}
test $# -ne 2 && { echo "$pname: missing arguments.">&2; exit 1;}
$verbosep && {
  quietp=false
  lnopt=--verbose
}


saadir="$1"
newsaadir="$2"

test -d "$saadir" ||
  { echo "$saadir: source directory not exist.">&2; exit 2;}
test -d "$newsaadir" &&
  { echo "$newsaadir: the destination directory exists. Remove it and retry.">&2; exit 2;}
$quietp || echo "make $newsaadir.">&2
mkdir -p "$newsaadir"/"$appsdir" ||
  { echo "$newsaadir/$appsdir: mkdir failed.">&2; exit 3;}
for obj in apk ab; do
  $quietp || echo "make hardlinks for $obj.">&2
  ln${lnopt:+ $lnopt} "$saadir"/"$appsdir"/*.$obj "$newsaadir"/"$appsdir" ||
    { echo "$pname: abort.">&2; exit 4;}
done

(
  cd "$newsaadir"
  $quietp || echo "make @list.">&2
  "$dname"/saa-make-list ||
    { echo "$pname: abort.">&2; exit 5; }
  #"$dname"/saa-make-desc ||
  #  { echo "$pname: abort.">&2; exit 6; }
)
$quietp || echo "copy $blacklist.">&2
cp "$saadir"/"$blacklist" "$newsaadir"/ ||
  { echo "$pname: abort.">&2; exit 7; }
