#!/bin/bash
pname=$(basename "$0")
dname=$(dirname "$0")
source "$dname/saa-environ.sh"
case "$dname" in /*);; *) dname="$(pwd)/$dname";; esac
usage="$pname [Options] ApkVerListFile1 ApkVerListFile2 [...]
$pname {-h|--help}
Features:
  Merge two or more PackgakeList or ApkVerListFile with prefix for apk file path.
  The default output is to stdout.
Options:
  -c|--stdout|--to-stdout (not yet implemented)
    output to stdout (default: output to $verlist).
  -h|--help
    This help message is displayed."

stdoutp=false
helpp=false
opterrp=false
declare -a opts
while true; do
  case "$1" in
  -|--) break;;
  --*) opts=("$1"); shift;;
  -*) for n in $(seq 1 $((${#1}-1))); do opts[$n]="-${1:$n:1}"; done; shift;;
  *) break;;
  esac
  for opt in "${opts[@]}"; do
    case "$opt" in
    -c|--stdout|--to-stdout) stdoutp=true;;
    -h|--help) helpp=true;;
    -*) echo "$opt: unknown option.">&2; opterrp=true;;
    esac
  done
done
$opterrp && exit 1
$helpp && { echo "$usage"; exit;}
test $# -lt 2 &&
  { echo "$pname: requires two or more arguments.">&2; exit 1; }

for file; do
  prefix="$(dirname $file | sed 's/|/\\|/')"
  sed "s|\$|	$prefix/$appsdir/|" "$file"
done | sort -k 1 | sed 's/^\(.*\)	\([^	]*\)$/\2\1/'
